version: '3.9'
services:
  php:
    image: wodby/php:latest
    volumes:
      - './:/var/www/html'
    depends_on:
      - mariadb

  nginx:
    image: nginx:latest
    ports:
      - 88:80
      - 881:443
    links:
      - 'php'
    volumes:
      - './:/var/www/html'
      - './docker/nginxcert/cert.crt:/etc/nginx/cert.crt'
      - './docker/nginxcert/cert.key:/etc/nginx/cert.key'
      - './docker/nginx:/etc/nginx/conf.d'
    depends_on:
      - php

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: m6prog
      MYSQL_USER: m6user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: bfduvxijkn367GYUB_uibfesd#
    ports:
      - 3308:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: bfduvxijkn367GYUB_uibfesd#
    ports:
    - "1088:80"